apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketingexpiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketingexpiration
  template:
    metadata:
      labels:
        app: ticketingexpiration
    spec:
      containers:
        - name: ticketingexpiration
          image: williangrios/ticketingexpiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom: # AQUI PEGAMOS O ID DO POD
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: ticketingexpiration-redis-srv
