apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketingorders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketingorders
  template:
    metadata:
      labels:
        app: ticketingorders
    spec:
      containers:
        - name: ticketingorders
          image: williangrios/ticketingorders
          env:
            - name: NATS_CLIENT_ID
              valueFrom: # AQUI PEGAMOS O ID DO POD
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://ticketingorders-mongo-srv:27017/ticketingorders'
            # - name: JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: jwt-secret
            #       key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticketingorders-srv
spec:
  selector:
    app: ticketingorders
  ports:
    - name: ticketingorders
      protocol: TCP
      port: 3000
      targetPort: 3000
