### Requisição GET para not found
GET http://ticketing.dev/api/users/notexists

### Requisição POST para Signup
POST https://ticketing.dev/api/users/signup
Content-Type: application/json

{
  "email": "willian@gmail.com",
  "password": "pwdWillian"
}

### Requisição POST com dados inválidos (email inválido)
POST https://ticketing.dev/api/users/signup

Content-Type: application/json
{
  "email": "invalid-email",
  "password": "12"
}