name: tests-ticketingpayments

on:
  pull_request:
    paths:
      - 'ticketingpayments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketingpayments && npm install && npm run test:ci
